spring:
  datasource:
    url: jdbc:h2:~/test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
github:
  tester:
    user-name: jipark3
    repository-name: doms-react
    access-token: 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

