spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:~/test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

logging:
  config: classpath:log4j2/log4j2-test.xml
