spring:
  datasource:
    url: jdbc:mariadb://localhost:13306/pickgit?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: false
    hibernate:
      ddl-auto: none
