spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pickgit?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: true
    hibernate:
      ddl-auto: none
