spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: jdbc:mariadb://localhost:13306/pickgit?serverTimezone=UTC&characterEncoding=UTF-8
    username: master
    password: passwd
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 1000
      jdbc:
        lob:
          non_contextual_creation: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

security:
  github:
    client:
      id: abc
      secret: def
    url:
      redirect: http://dev.pick-git.com/auth

logging:
  config: classpath:log4j2/log4j2-dev.xml
