create table comment
(
    id      bigint generated by default as identity,
    content clob not null,
    post_id bigint,
    user_id bigint,
    primary key (id)
);

create table contact
(
    id           bigint generated by default as identity,
    category     varchar(255) not null,
    value        varchar(255) not null,
    portfolio_id bigint       not null,
    primary key (id)
);

create table description
(
    id      bigint generated by default as identity,
    value   varchar(255),
    item_id bigint,
    primary key (id)
);

create table follow
(
    id        bigint generated by default as identity,
    source_id bigint,
    target_id bigint,
    primary key (id)
);

create table image
(
    id      bigint generated by default as identity,
    url     varchar(255) not null,
    post_id bigint,
    primary key (id)
);

create table item
(
    id         bigint generated by default as identity,
    category   varchar(255),
    section_id bigint,
    primary key (id)
);

create table likes
(
    id      bigint generated by default as identity,
    post_id bigint,
    user_id bigint,
    primary key (id)
);

create table portfolio
(
    id                  bigint generated by default as identity,
    introduction        varchar(255),
    profile_image_shown boolean      not null,
    profile_image_url   varchar(255) not null,
    primary key (id)
);

create table post
(
    id              bigint generated by default as identity,
    content         clob,
    created_at      timestamp,
    github_repo_url varchar(255),
    updated_at      timestamp,
    user_id         bigint,
    primary key (id)
);

create table post_tag
(
    id      bigint generated by default as identity,
    post_id bigint not null,
    tag_id  bigint not null,
    primary key (id)
);

create table project
(
    id           bigint generated by default as identity,
    content      varchar(255),
    end_date     timestamp,
    image_url    varchar(255) not null,
    name         varchar(255) not null,
    start_date   timestamp,
    type         integer      not null,
    portfolio_id bigint       not null,
    primary key (id)
);

create table project_tag
(
    id         bigint generated by default as identity,
    project_id bigint,
    tag_id     bigint,
    primary key (id)
);

create table section
(
    id           bigint generated by default as identity,
    name         varchar(255) not null,
    portfolio_id bigint,
    primary key (id)
);

create table tag
(
    id   bigint generated by default as identity,
    name varchar(20) not null,
    primary key (id)
);

create table user
(
    id          bigint generated by default as identity,
    description varchar(255),
    image       varchar(255),
    name        varchar(255) not null,
    company     varchar(255),
    github_url  varchar(255) not null,
    location    varchar(255),
    twitter     varchar(255),
    website     varchar(255),
    primary key (id)
);

alter table follow
    add constraint uk_follow_source_target unique (source_id, target_id);

alter table tag
    add constraint uk_tag_name unique (name);

alter table comment
    add constraint fk_comment_to_post
        foreign key (post_id)
            references post;

alter table comment
    add constraint fk_comment_to_user
        foreign key (user_id)
            references user;

alter table contact
    add constraint fk_contact_to_portfolio
        foreign key (portfolio_id)
            references portfolio;

alter table description
    add constraint fk_description_to_item
        foreign key (item_id)
            references item;

alter table follow
    add constraint fk_follow_to_source
        foreign key (source_id)
            references user;

alter table follow
    add constraint fk_follow_to_target
        foreign key (target_id)
            references user;

alter table image
    add constraint fk_image_to_post
        foreign key (post_id)
            references post;

alter table item
    add constraint fk_item_to_section
        foreign key (section_id)
            references section;

alter table likes
    add constraint fk_like_to_post
        foreign key (post_id)
            references post;

alter table likes
    add constraint fk_like_to_user
        foreign key (user_id)
            references user;

alter table post
    add constraint fk_post_to_user
        foreign key (user_id)
            references user;

alter table post_tag
    add constraint fk_post_tag_to_post
        foreign key (post_id)
            references post;

alter table post_tag
    add constraint fk_post_tag_to_tag
        foreign key (tag_id)
            references tag;

alter table project
    add constraint fk_project_to_portfolio
        foreign key (portfolio_id)
            references portfolio;

alter table project_tag
    add constraint fk_project_tag_to_project
        foreign key (project_id)
            references project;

alter table project_tag
    add constraint fk_project_tag_to_tag
        foreign key (tag_id)
            references tag;

alter table section
    add constraint fk_section_to_portfolio
        foreign key (portfolio_id)
            references portfolio;
