export const QUERY = {
  GET_PROFILE: "GET_SELF_PROFILE",
  GET_HOME_FEED_POSTS: "GET_HOME_FEED_POSTS",
  GET_USER_FEED_POSTS: "GET_USER_FEED_POSTS",
  GET_GITHUB_STATS: "GET_GITHUB_STATS",
  GET_GITHUB_REPOSITORIES: "GET_GITHUB_REPOSITORIES",
  GET_GITHUB_TAGS: "GET_GITHUB_TAGS",
  ADD_POST_LIKE: "ADD_POST_LIKE",
  DELETE_POST_LIKE: "DELETE_POST_LIKE",
};
