import { FeedFilterOption } from "../@types";

export const QUERY = {
  GET_PROFILE: "GET_SELF_PROFILE",
  GET_PROFILE_FOLLOWING: "GET_PROFILE_FOLLOWING",
  GET_PROFILE_FOLLOWER: "GET_PROFILE_FOLLOWER",
  GET_HOME_FEED_POSTS: (feedOption: FeedFilterOption) => `GET_HOME_FEED_POSTS?${feedOption}`,
  GET_USER_FEED_POSTS: "GET_USER_FEED_POSTS",
  GET_SEARCH_USER_RESULT: "GET_SEARCH_USER_RESULT",
  GET_SEARCH_POST_RESULT: "GET_SEARCH_POST_RESULT",
  GET_GITHUB_STATS: "GET_GITHUB_STATS",
  GET_GITHUB_REPOSITORIES: "GET_GITHUB_REPOSITORIES",
  GET_GITHUB_TAGS: "GET_GITHUB_TAGS",
  GET_POST_COMMENTS: "GET_POST_COMMENTS",
  GET_POST_LIKE_PEOPLE: "GET_POST_LIKE_PEOPLE",
  GET_PORTFOLIO: "GET_PORTFOLIO",
  GET_POST: "GET_POST",
  ADD_POST_LIKE: "ADD_POST_LIKE",
  DELETE_POST_LIKE: "DELETE_POST_LIKE",
};
